sudo: required
services:
  - docker

before_install:
  - docker build -t justintillman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true justintillman/react-test npm test -- --coverage

after_success:
  - docker build -t justintillman/multi-api ./api
  - docker build -t justintillman/multi-client ./client
  - docker build -t justintillman/multi-nginx ./nginx
  - docker build -t justintillman/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push justintillman/multi-api
  - docker push justintillman/multi-client
  - docker push justintillman/multi-nginx
  - docker push justintillman/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-017851380870
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
